name: React CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build
        
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build Docker Image
        run: docker build -t react-github-actions .    